import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Aldrich } from "next/font/google";
import ThemeFab from "./components/themeFab";
import Footer from "./components/footer";
import Navbar from "./components/navbar";
import LiveWallpaper from "./components/liveWallpaper";
import Preloader from "./components/preloader";
import { PreloaderProvider } from "./contexts/PreloaderContext";
import ConfirmEmail from "./components/confirmEmail";
import AuthProvider from "./components/authProvider";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const aldrich = Aldrich({ subsets: ["latin"], weight: ["400"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      data-theme="light"
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={`${aldrich.className} min-h-full flex flex-col`}>
        <AuthProvider>
          <PreloaderProvider>
            <Preloader />
            <LiveWallpaper />
            <ConfirmEmail />
            <Navbar />
            {children}
            <Footer />
            <ThemeFab />
          </PreloaderProvider>
        </AuthProvider>
      </body>
    </html>
  );
}